language: swift
osx_image: xcode11.2
cache:
  bundler: true
  directories:
    - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
script:
  - bundle exec fastlane ios tests
